const QUESTIONS = [
  {
    id: 1,
    text: "Is a computer alive like you?",
    answers: ["Yes", "No"],
    correctAnswer: "No",
    level: 1,
    title: "Meet the Computer",
    storyline: "A friendly robot (Lulu) introduces itself.",
    reward: "🏅 Computer Explorer",
  },
  {
    id: 2,
    text: "Can a computer work without a screen?",
    answers: ["Yes", "No"],
    correctAnswer: "No",
    level: 2,
    title: "Parts of a Computer",
    storyline: "Lulu shows you a keyboard and screen.",
    reward: "🎖 Keyboard Hero",
  },
  {
    id: 3,
    text: "Is the CPU like the brain of the computer?",
    answers: ["Yes", "No"],
    correctAnswer: "Yes",
    level: 3,
    title: "Brain of the Computer",
    storyline: "Lulu points to the CPU.",
    reward: "🏆 Brainy Explorer",
  },
  {
    id: 4,
    text: "Does the computer forget things when you turn it off?",
    answers: ["Yes", "No"],
    correctAnswer: "Yes",
    level: 4,
    title: "Memory Time",
    storyline: "Lulu talks about saving and remembering things.",
    reward: "💾 Memory Keeper",
  },
  {
    id: 5,
    text: "Is the mouse an input device?",
    answers: ["Yes", "No"],
    correctAnswer: "Yes",
    level: 5,
    title: "Input Devices",
    storyline: "Lulu shows a mouse and keyboard.",
    reward: "🖱 Input Pro",
  },
  {
    id: 6,
    text: "Is a printer an output device?",
    answers: ["Yes", "No"],
    correctAnswer: "Yes",
    level: 6,
    title: "Output Devices",
    storyline: "Lulu turns on a monitor.",
    reward: "🖨 Output Master",
  },
  {
    id: 7,
    text: "Can hardware run without software?",
    answers: ["Yes", "No"],
    correctAnswer: "No",
    level: 7,
    title: "Software & Hardware",
    storyline: "Lulu explains how software tells hardware what to do.",
    reward: "💡 Tech Thinker",
  },
  {
    id: 8,
    text: "Do computers need electricity to work?",
    answers: ["Yes", "No"],
    correctAnswer: "Yes",
    level: 8,
    title: "Let’s Play",
    storyline: "Lulu runs a fun game!",
    reward: "⚡ Power Genius",
  },
];

export default QUESTIONS;
